version: "3.7"

services:
  app:
    restart: unless-stopped
    container_name: app_python37
    build: 
      context: .
      dockerfile: Dockerfile
    env_file: src/.env
###    command: ["python", "generate.py"]
    command: tail -F anything
    volumes:
      - ./logs:/dist/logs
    
    networks:
        - frontend
        - backend

    depends_on:
        - db  
      
  db:
    container_name: data_sqlserver
    image: mcr.microsoft.com/mssql/server:2017-latest
    env_file: src/.env
    environment:
      - SA_PASSWORD=Passw0rd
      - ACCEPT_EULA=Y

    networks:
      - backend
volumes: 
    db:

networks:
    frontend:
        driver: bridge

    backend: 
        driver: bridge
